name: Docker CI

on:
  push:
    tags:    # Pattern matched against refs/tags
      - '*'

  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows to run this workflow from the Actions tab
  workflow_dispatch:

env:
  FOLDER: "."
  REGISTRY: ${{ secrets.DESCIL_REGISTRY_URL }}
  ORG: descil
  REPO: datascience
  LABEL: codetect
  FRONTEND_LABEL: codetect-frontend
  NS: led

jobs:
  build:
    runs-on: descil-runners

    steps:
    - uses: actions/checkout@v4

    - name: Get latest tag pushed
      id: tag
      uses: 32teeth/action-github-tag@v1.0.7
      if: startsWith(github.ref, 'refs/tags/')

    - name: Set TAG variable
      id: set_tag
      run: |
        if [ -z "${{ steps.tag.outputs.tag }}" ]; then
          echo "tag=latest" >> $GITHUB_OUTPUT
        else
          echo "tag=${{ steps.tag.outputs.tag }}" >> $GITHUB_OUTPUT
        fi

    - name: Show tag used
      run: echo ${{ steps.set_tag.outputs.tag }}

    - name: Login to GitLab
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DESCIL_REGISTRY_URL }}
        username: ${{ secrets.DESCIL_REGISTRY_USER }}
        password: ${{ secrets.DESCIL_REGISTRY_PASSWORD }}

    - name: Build the Backend Docker image
      run: docker build . --file $FOLDER/Dockerfile --tag $REGISTRY/$ORG/$REPO/$LABEL:${{steps.set_tag.outputs.tag}} --build-arg http_proxy="http://proxy.ethz.ch:3128" --build-arg https_proxy="http://proxy.ethz.ch:3128"

    - name: Push the Backend Docker image
      run: docker push $REGISTRY/$ORG/$REPO/$LABEL:${{steps.set_tag.outputs.tag}}

    - name: Tag the Backend Docker image as latest
      run: docker tag $REGISTRY/$ORG/$REPO/$LABEL:${{steps.set_tag.outputs.tag}} $REGISTRY/$ORG/$REPO/$LABEL:latest

    - name: Push Backend latest tag
      run: docker push $REGISTRY/$ORG/$REPO/$LABEL:latest

    - name: Build the Frontend Docker image
      run: docker build . --file $FOLDER/Dockerfile_frontend --tag $REGISTRY/$ORG/$REPO/$FRONTEND_LABEL:${{steps.set_tag.outputs.tag}} --build-arg http_proxy="http://proxy.ethz.ch:3128" --build-arg https_proxy="http://proxy.ethz.ch:3128"

    - name: Push the Frontend Docker image
      run: docker push $REGISTRY/$ORG/$REPO/$FRONTEND_LABEL:${{steps.set_tag.outputs.tag}}

    - name: Tag the Frontend Docker image as latest
      run: docker tag $REGISTRY/$ORG/$REPO/$FRONTEND_LABEL:${{steps.set_tag.outputs.tag}} $REGISTRY/$ORG/$REPO/$FRONTEND_LABEL:latest

    - name: Push Frontend latest tag
      run: docker push $REGISTRY/$ORG/$REPO/$FRONTEND_LABEL:latest
